[package]
name = "bofh"
version = "0.0.10"
authors = ["Tobias V. Langhoff"]
edition = "2024"
description = "Command-line client for the Cerebrum IGA"
license = "MIT"
repository = "https://github.com/tobiasvl/bofh-rs"
documentation = "https://docs.rs/bofh"
categories = ["api-bindings", "command-line-utilities"]

[dependencies]
xmlrpc = "0.15"
thiserror = "1.0"
rustyline = "13"
rustyline-derive = "0.10"
clap = { version = "4", features = ["derive"] }
whoami = "1.6"
rpassword = "7.5"
colored = "2.2"
