[package]
name = "bofh"
version = "0.0.11"
authors = ["Tobias V. Langhoff"]
edition = "2024"
description = "Command-line client for the Cerebrum IGA"
license = "MIT"
repository = "https://github.com/tobiasvl/bofh-rs"
documentation = "https://docs.rs/bofh"
categories = ["api-bindings", "command-line-utilities"]

[dependencies]
xmlrpc = "0.15"
iso8601 = "0.4" # Used in xmlrpc Values
thiserror = "2.0"
rustyline = "18"
rustyline-derive = "0.12"
clap = { version = "4", features = ["derive"] }
whoami = "2.1"
rpassword = "7.5"
colored = "3.1"
